### ISSUE TITLE
6.1 下载主题资源

### ISSUE THREAD

**Issue by shuoqiu** [limedroid/HexoLearning#3]
在cd到theme文件夹之后，会从github上下载资源，您给出的命令是：git clone clone https://github.com/iissnan/hexo-theme-next themes/next，这条命令我复制执行之后会出现如下错误提示：

`Too many arguments.
usage: git clone [<options>] [--] <repo> [<dir>]
    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recursive           initialize submodules in the clone
    --recurse-submodules  initialize submodules in the clone
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --single-branch       clone only one branch, HEAD or --branch
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only`
提示参数过多，看了下直接改成 https://github.com/iissnan/hexo-theme-next,
去掉参数就可以正常clone。

**Comment by limedroid** [comment]
应该是git clone 主题url
